### ISSUE TITLE
Migration vers Géocodeur GPF

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-bal#19]
Migrer nos utilisations du geocodeur vers celui de la GPF quand il sera disponible si les fonctionnalités et les performances sont conformes aux attentes de la BAN

```[tasklist]
### BAN
- [ ] https://github.com/BaseAdresseNationale/ban-bal/issues/61
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1662
```

**Comment by vinsag** [comment]
Mis en place sur le nouveau site adresse.data.gouv.fr
