### ISSUE TITLE
Définir le Standard Adresse

### ISSUE THREAD

**Issue by nkokla** [BaseAdresseNationale/ban-bal#30]

**Comment by FrederiqWilliams** [comment]
Définir la partie BAN du standard Adresse : formaliser le modèle de données principalement.

**Comment by mmortier** [comment]
Présentation au CNIG prévue @FrederiqWilliams on peut clore le ticket?

**Comment by FrederiqWilliams** [comment]
Prj de standard finalisé. Lancement de l'appel à commentaires CNIG le 02 Avril 2024. 
Le ticket peut être fermé.
