### ISSUE TITLE
COG 2023 : mise à jour des communes

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-bal#37]
Avant de mettre à jour les communes suite au fusion et renommage du COG 2023, il faut : 

```[tasklist]
### Pre-requis
- [x] MAJ decoupage (Etalab). La version actuellement utilisée dans ban-plateforme "@etalab/decoupage-administratif": "^2.0.0",
- [x] MAJ contours-admin (Etalab). La version actuellement utilisée dans ban-plateforme "https://adresse.data.gouv.fr/data/contours-administratifs/2022/geojson/communes-50m.geojson"
- [x] Mettre à jour les communes anciennes sur OSM (CQ)
```

```[tasklist]
### Etalab
- [x] MAJ de 'API Geo' (Millésime 2023)
- [x] Tuiles vectorielles à jour avec le découpage administratif
```

```[tasklist]
### BAL
- [ ] https://github.com/BaseAdresseNationale/annuaire-api/pull/5
- [ ] https://github.com/BaseAdresseNationale/validateur-bal/pull/71
- [ ] https://github.com/BaseAdresseNationale/api-depot/pull/71
- [ ] https://github.com/BaseAdresseNationale/mes-adresses-api/pull/371
- [ ] https://github.com/BaseAdresseNationale/mes-adresses-api/pull/370
- [ ] https://github.com/BaseAdresseNationale/moissonneur-bal/pull/56
- [ ] https://github.com/BaseAdresseNationale/mes-adresses/pull/750
- [ ] https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1469
```

```[tasklist]
### BAN
- [ ] https://github.com/BaseAdresseNationale/codes-postaux/issues/47
- [ ] https://github.com/BaseAdresseNationale/adresses-ftth/issues/17
- [ ] https://github.com/BaseAdresseNationale/adresses-cadastre/issues/25
- [ ] https://github.com/BaseAdresseNationale/fantoir/issues/21
- [ ] https://github.com/BaseAdresseNationale/gazetteer/issues/13
- [x] https://github.com/BaseAdresseNationale/ban-plateforme/issues/84
- [x] Copier les nouvelles bases fantoir et gazetteer dans data
```

```[tasklist]
### Taches à faire suite à la montée de version de BAN-Plateforme 
- [ ] https://github.com/BaseAdresseNationale/ban-plateforme/issues/77
```

TODO: Documenter et etudier la possibilité d'automatiser.

**Comment by mmortier** [comment]
Il faut ensuite que Gazetteer soit mis à jour, ainsi que les codes postaux.
Lancer ensuite le script update cog

**Comment by mmortier** [comment]
https://www.insee.fr/fr/information/6800675 le COG 2023 a été publié le 17/02/2023

**Comment by FrederiqWilliams** [comment]
Besoin lié : les fusions de communes génèrent des doublons de noms de voies. Il faut définir le dispositif permettant de distinguer ces doublons. 

 les champs "Ancienne_commune_nom" et ancienne_commune_INSEE" sont remplis automatiquement lors de l'intégration du COG. Ces champs ne sont pour l'instant pas mis à disposition des utilisateurs. 
Amélioration : 
voir la façon de les mettre à disposition : 
- dans les exports (à vérifier il sont sans doute dans l'export au format BAL)
- dans l'explorateur : prévoir un moyen de remonter l'info ancienne acommune dans le libellé? 
- -dans l'API Adresse

**Comment by antoineludeau** [comment]
Infos supplémentaires 
- La ban-plateforme gère elle-même les fusions de commune.
- La ban-plateforme ne gère pas les scission de commune.
- Les voies sont tronçonnées par la fusion des communes pour garder le nom des anciennes commune sur le tronçon qui a été fusionné (et uniquement sur ce tronçon).
- Lors de la recherche du code fantoir ou du code postal, on commence par chercher avec le code de l'ancienne commune car dans les données de la DGFiP de janvier, les communes ne sont pas encore fusionnées. S’il n’est pas trouvé avec le code de l’ancienne commune, on cherche avec le code de la nouvelle commune.
