### ISSUE TITLE
Collectivités d'outremer

### ISSUE THREAD

**Issue by jdesboeufs** [BaseAdresseNationale/ban-bal#4]
L'objectif de ce sujet est de s'assurer que tous les composants de la Base Adresse Nationale (au sens large) couvrent bien les collectivités d'outremer (et pas seulement les DROM).

Des ajustements sont probablement nécessaires à différents endroits.

### API Géo

https://github.com/etalab/api-geo

L'API Géo retourne actuellement les communes d'une COM sous une forme spécifique, sans département, sans région (normal), ce qui pose problème dans les différents composants UI qui l'utilise (adresse.data.gouv.fr, mes-adresses).

https://github.com/etalab/api-geo/issues/154

### Découpage administratif

https://github.com/etalab/decoupage-administratif

S'assurer de la complétude du référentiel

### Contours administratifs

https://github.com/etalab/contours-administratifs

Les fichiers `contours-administratifs` ont quelques contours manquants (Wallis-et-Futuna, commune de Gambier).
Même problème pour les tuiles vectorielles associées.

https://github.com/etalab/contours-administratifs/issues/17
https://github.com/etalab/contours-administratifs/issues/18
- Ticket pour l'intégration des contours-administratifs de nouvelle calédonie avec le site officiel georep.nc
https://github.com/etalab/contours-administratifs/issues/21

### API Annuaire

L'API Annuaire ne couvre pas certains territoires.
Il faut expliciter les territoires non couverts et proposer des alternatives partout où c'est nécessaire.

### FranceConnect et RNE

FranceConnect et le RNE ne couvrent pas certains territoires.
Il faut expliciter les territoires non couverts et proposer des alternatives partout où c'est nécessaire.

### Cadastre

Pas de cadastre disponible pour certaines territoires.

### API Habilitation

Certains territoires n'auront aucune stratégie d'authentification disponible. Il faudra donc imaginer une stratégie de contournement (nous contacter ?)

### Fonds de carte IGN non disponibles

Pas de Plan IGN et pas de photographie aériennes IGN sur la plupart de ces territoires.

### Mes Adresses

Impacté par API Habilitation, API Géo, Contours administratifs, Fonds de carte
Cf ticket dédié https://github.com/BaseAdresseNationale/mes-adresses/issues/531

### Bibliothèque project-legal

https://github.com/BaseAdresseNationale/project-legal

Élargir le périmètre de la bibliothèque en intégrant les projections légales des COM quand elles existent.

### BAN

Revoir les listing internes pour intégrer les communes des COM
Revoir les sources pour extraire les quelques COM qu'on a déjà via les sources IGN et Cadastre (Saint-Pierre-et-Miquelon, Saint-Barthélémy, Saint-Martin)
Prévoir l'export pour tous ces nouveaux territoires.

https://github.com/BaseAdresseNationale/ban-plateforme/issues/19

### Récapitulatif

- [x] https://github.com/BaseAdresseNationale/ban-plateforme/issues/19
- [x] https://github.com/etalab/api-geo/issues/154
- [x] https://github.com/BaseAdresseNationale/project-legal/issues/153
- [x] https://github.com/BaseAdresseNationale/mes-adresses/issues/531
- [x] https://github.com/etalab/contours-administratifs/issues/17
- [x] https://github.com/etalab/contours-administratifs/issues/18
- [x] https://github.com/etalab/contours-administratifs/issues/21

**Comment by mmortier** [comment]
Pour Bibliothèque project-legal https://github.com/BaseAdresseNationale/project-legal/issues/153

**Comment by mmortier** [comment]
Pour **Bibliothèque project-legal** https://github.com/BaseAdresseNationale/project-legal/issues/153

**Comment by jdesboeufs** [comment]
En production.

Il restera à suivre les évolutions de l'API Géo. En attendant c'est opérationnel.
