### ISSUE TITLE
FDR : Bibliothèque de composants graphiques réutilisables

### ISSUE THREAD

**Issue by mmortier** [BaseAdresseNationale/ban-bal#8]
Créer une bibliothèque de composants réutilisables pour partager les composants entre le site de Mes Adresses et adresse.data.gouv.
Voir pour ne pas charger toute la bibliothèque d'un coup mais que la partie qui nous intéresse (rollup -> babel?).
ticket Mes adresses  : https://github.com/BaseAdresseNationale/mes-adresses/issues/495

**Comment by jdesboeufs** [comment]
Le chantier est abandonné pour le moment.
Il faudra le reprendre de zéro, l'avancement n'était qu'au stade expérimental et a heurté quelques difficultés.
